Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace AdviceGeneratorWebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using System;
using System.Net.Http;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace AdviceGeneratorWebApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }
        public IActionResult OnGetRefresh()
        {
            return RedirectToPage("Index");
        }


        [BindProperty(SupportsGet = true)]
        public adviceResponseObj? deserialAdvice { get; set; }
        public async Task OnGetAsync()
        {
           var client = new HttpClient();
            var adviceUrl = "https://api.adviceslip.com/advice";
            var adviceResponse = await client.GetAsync(adviceUrl);
            adviceResponse.EnsureSuccessStatusCode();
            var responseContent = await adviceResponse.Content.ReadAsStringAsync();
             deserialAdvice = JsonConvert.DeserializeObject<adviceResponseObj>(responseContent);
        }
    }
}

public class adviceResponseObj
{
    public adviceInnerObj slip { get; set; }
}

public class adviceInnerObj
{
    public int id { get; set; }
    public string advice { get; set; }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AdviceGeneratorWebApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Index.cshtml
@page "/Home"
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="card-body bg-success p-4 rounded-3 shadow-lg d-flex flex-column col-lg-4 mx-md-5 align-items-center my-5 mx-lg-auto mx-3">
   <div>
       @if (Model.deserialAdvice != null)
       {
            <h4 class="text-light fw-bold text-center ">"@Model.deserialAdvice.slip.advice"</h4>
       }
        else
        {
            <h4 class="text-center text-danger"> Sorry your internet connection is not strong enough to get an advice.</h4>
        }
    </div>
   <div class="d-flex my-2"><hr /><img src="./images/pattern-divider-desktop.svg" class="img-fluid" /><hr /></div>
    
    <a class="btn btn-primary btn-sm dice-btn rounded-pill p-2 text-center" asp-page-handler="Refresh"><img src="./images/icon-dice.svg" class="img-fluid" /></a> 
</div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AdviceGeneratorWebApp</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AdviceGeneratorWebApp.styles.css" asp-append-version="true" />
</head>
<body class="bg-dark">
    <header class="mb-4">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Advice<span class="text-success h4">G</span>enerator</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 gap-md-4">
                        <li class="nav-item">
                            <a class="nav-link fw-bold" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link fw-bold" asp-area="" asp-page="/Privacy">Buy me a coffee</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="d-flex align-items-center my-5 flex-column">
        <main role="main" class="col-12 my-5 bg-dark">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AdviceGeneratorWebApp - <a href="https://wa.me/message/6I6HYY55CRIDL1">ContactUs</a>
            created by Codex&copy;
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>